[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Optional: force www -> apex or vice versa after DNS set
[[redirects]]
  from = "https://www.gebriggs.com/*"
  to = "https://gebriggs.com/:splat"
  status = 301
